# Generated by Django 3.0.7 on 2020-07-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinex', '0002_rinexmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rinexmetadata',
            name='file_rinex',
            field=models.CharField(max_length=150),
        ),
    ]
