# Generated by Django 3.0.7 on 2020-09-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinex', '0003_auto_20200716_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='rinexmetadata',
            name='licence',
            field=models.CharField(default='CC0', max_length=300),
        ),
    ]
