# Generated by Django 3.0.7 on 2020-09-22 17:08

from django.db import migrations, models
import rinex.models


class Migration(migrations.Migration):

    dependencies = [
        ('rinex', '0003_auto_20200716_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='rinexmetadata',
            name='licence',
            field=models.CharField(choices=[(rinex.models.TypeOfLicence['CC_BY_IGO'], 'Creative Commons Attribution for Intergovernmental Organisations (CC BY-IGO)'), (rinex.models.TypeOfLicence['CC_BY'], 'Creative Commons Attribution International\t(CC BY)'), (rinex.models.TypeOfLicence['CC_BY_SA'], 'Creative Commons Attribution-Share Alike (CC BY-SA)'), (rinex.models.TypeOfLicence['CC0'], 'Public Domain - No restrictions (CC0)'), (rinex.models.TypeOfLicence['ODC_ODbL'], 'Open Database License (ODC-ODbL)'), (rinex.models.TypeOfLicence['ODC_BY'], 'Open Data Commons Attribution License (ODC-BY)'), (rinex.models.TypeOfLicence['PDDL'], 'Open Data Commons Public Domain Dedication and License (PDDL)')], default=(rinex.models.TypeOfLicence['CC0'], 'Public Domain - No restrictions (CC0)'), max_length=300),
        ),
    ]
